#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/7c581997-6a52-47e4-863b-75cded19ef4a 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int moisture;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
const int pumpPin = 13;
const int soilSensor = A1;
const int dry = 300;


void setup() {
  pinMode(pumpPin, OUTPUT);
  pinMode(soilSensor, INPUT);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // read current moisture
  moisture = analogRead(soilSensor);
  Serial.println(moisture);
  delay(1000);
  
  if (moisture >= dry) {
    
    Serial.println("Watering starts now!");
    Serial.println("Moisture is " + String(moisture));
    digitalWrite(pumpPin, LOW);

    // keep watering for 3 sec
    delay(3000);

    // turn off water
    digitalWrite(pumpPin, HIGH);
    Serial.println("Done watering!");
  } 
  else {
    Serial.println("Moisture is good, no watering is needed " + String(moisture));
  }
}
